### ISSUE TITLE
test imgs resize to 640*640?

### ISSUE THREAD

**Issue by guyiyifeurach** [singetta/OnnxSample#1]
Thanks for your work. I have a problem puzzles me, where in YoloDetector.cs, interface of CreateLetterbox.
As I think, the interface need change test imgs to model's entrance interface, such as 640 * 640.
But the newUnpad parameter is the new image size of test img. And in many cases of input, newUnpad will not be equal to 640.
So the inference will produce error.
![image](https://user-images.githubusercontent.com/32059046/138593047-9414a6f1-cf0c-4765-a5f5-c14de440f12c.png)

**Comment by singetta** [comment]
@guyiyifeurach // I'm sorry for the late. in python code, yolo v5 model is adaptive image rescaling in inference time. so if you had run `detect.py` in yolov5 repository, you can see that the input image has rescaled like the image below
![스크린샷 2022-03-22 오후 7 50 19](https://user-images.githubusercontent.com/11040628/159466155-7bc72ff6-db25-4397-acaa-f96a77142286.png)
in my case, train input image is 640x640 but inference(test) input image is 384x640. so i created onnix version model that use 384x640 input.
`python models\export.py --weights runs\train\exp\weights\best.pt --batch 1 --simplify --img-size 384 640` and i created letterbox 384x640. (see below code)
https://github.com/singetta/OnnxSample/blob/5c01d106a4633bede0935c6ad38bafad9bd3dc8c/OnnxSample/Program.cs#L16
